version: "3.9"  # optional since v1.27.0
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  proxy:
    image: mbao01/raft-node:latest
    ports:
      - "8888:8080"
    volumes:
      - .:/raft
    depends_on:
      redis:
        condition: service_started
    environment:
      - API=EXTERNAL
  node:
    image: mbao01/raft-node:latest
    scale: 5
    volumes:
      - .:/raft
    depends_on:
      redis:
        condition: service_started

networks:
  default:
    name: raft-network
    driver: bridge
